# LAB4 : Implement Decision tree algorithm for classification

## Import Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## import Dataset

In [29]:
dataset =  pd.read_csv('/content/diabetes.csv')

## EDA Steps

In [41]:
dataset.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [42]:
dataset.shape

(768, 9)

In [43]:
dataset.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [44]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [45]:
dataset.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

## Preprocessing Steps

## Step 1 : Seprate input and output variables

In [46]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

### Step 4 : splitting Data inti training and testing

In [47]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,
                                    test_size = 0.25,
                                    random_state = 0)

In [49]:
print(X_train.shape)
print(X_test.shape)

(576, 8)
(192, 8)

In [50]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)

In [51]:
print(X_test)

[[  1.    199.     76.    ...  42.9     1.394  22.   ]
 [  2.    107.     74.    ...  33.6     0.404  23.   ]
 [  4.     76.     62.    ...  34.      0.391  25.   ]
 ...
 [  1.    109.     60.    ...  25.4     0.947  21.   ]
 [  3.    128.     78.    ...  21.1     0.268  55.   ]
 [  5.     88.     78.    ...  27.6     0.258  37.   ]]

In [55]:
dataset['Pregnancies'].value_counts()

Pregnancies
1     135
0     111
2     103
3      75
4      68
5      57
6      50
7      45
8      38
9      28
10     24
11     11
13     10
12      9
14      2
17      1
15      1
Name: count, dtype: int64

### Train the Decision Tree Classification model on the Training set

In [56]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy',random_state= 0,
                                    splitter='random',ccp_alpha =0.0001)

classifier.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0001, criterion='entropy', random_state=0,
                       splitter='random')

In [57]:
print(classifier.classes_)

[0 1]

In [58]:
classifier.max_features_

8

In [59]:
classifier.tree_

In [60]:
classifier.n_outputs_

1

#### Predicting the Test set results

In [61]:
ypred = classifier.predict(X_test)

In [62]:
print(ypred)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1]

#### Compare the predicted and Actual Output

In [63]:
print(np.concatenate((ypred.reshape(len(ypred),1),
                      y_test.reshape(len(y_test),1)),
                     1))

[[1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]]

### Making the Confusion Matrix

In [64]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, ypred)
print(cm)

[[  1 129]
 [  0  62]]

In [65]:
print("Accuracy =",(194+147)/343*100)

Accuracy = 99.41690962099126

In [66]:
from sklearn.metrics import accuracy_score
print("Test Accuracy =",accuracy_score(y_test,ypred))

Test Accuracy = 0.328125

#### Build the Classification Report

In [67]:
from sklearn.metrics import classification_report

print(classification_report(y_test,ypred))

              precision    recall  f1-score   support

           0       1.00      0.01      0.02       130
           1       0.32      1.00      0.49        62

    accuracy                           0.33       192
   macro avg       0.66      0.50      0.25       192
weighted avg       0.78      0.33      0.17       192

### Visualising the Training set results

#### VISUALIZE TEXT REPRESENTATION

In [68]:
!pip install -U scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.5.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.6.0)

In [70]:
## if not working update scikit learn package
## !pip install -U scikit-learn
from sklearn.tree import export_text
text_representation = export_text(classifier)
print(text_representation)

|--- feature_7 <= -0.32
|   |--- feature_1 <= 0.67
|   |   |--- feature_1 <= 0.27
|   |   |   |--- feature_5 <= -1.25
|   |   |   |   |--- class: 0
|   |   |   |--- feature_5 >  -1.25
|   |   |   |   |--- feature_5 <= 2.62
|   |   |   |   |   |--- feature_5 <= -0.54
|   |   |   |   |   |   |--- feature_0 <= 0.41
|   |   |   |   |   |   |   |--- feature_0 <= -0.45
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_0 >  -0.45
|   |   |   |   |   |   |   |   |--- feature_5 <= -1.12
|   |   |   |   |   |   |   |   |   |--- feature_6 <= -0.41
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_6 >  -0.41
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_5 >  -1.12
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- feature_0 >  0.41
|   |   |   |   |   |   |   |--- feature_5 <= -0.83
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_5 >  -0.83
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- feature_5 >  -0.54
|   |   |   |   |   |   |--- feature_6 <= 0.90
|   |   |   |   |   |   |   |--- feature_3 <= 0.14
|   |   |   |   |   |   |   |   |--- feature_3 <= -0.39
|   |   |   |   |   |   |   |   |   |--- feature_6 <= -0.27
|   |   |   |   |   |   |   |   |   |   |--- feature_2 <= 0.56
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5
|   |   |   |   |   |   |   |   |   |   |--- feature_2 >  0.56
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- feature_6 >  -0.27
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_3 >  -0.39
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_3 >  0.14
|   |   |   |   |   |   |   |   |--- feature_0 <= 0.84
|   |   |   |   |   |   |   |   |   |--- feature_7 <= -0.53
|   |   |   |   |   |   |   |   |   |   |--- feature_1 <= -1.05
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |   |   |   |--- feature_1 >  -1.05
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 9
|   |   |   |   |   |   |   |   |   |--- feature_7 >  -0.53
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_0 >  0.84
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_6 >  0.90
|   |   |   |   |   |   |   |--- feature_7 <= -0.89
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_7 >  -0.89
|   |   |   |   |   |   |   |   |--- feature_4 <= -0.35
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_4 >  -0.35
|   |   |   |   |   |   |   |   |   |--- feature_7 <= -0.77
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_7 >  -0.77
|   |   |   |   |   |   |   |   |   |   |--- feature_3 <= 1.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |   |   |   |--- feature_3 >  1.50
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- feature_5 >  2.62
|   |   |   |   |   |--- feature_3 <= 0.87
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_3 >  0.87
|   |   |   |   |   |   |--- class: 1
|   |   |--- feature_1 >  0.27
|   |   |   |--- feature_5 <= -0.57
|   |   |   |   |--- class: 0
|   |   |   |--- feature_5 >  -0.57
|   |   |   |   |--- feature_2 <= -2.48
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_2 >  -2.48
|   |   |   |   |   |--- feature_5 <= -0.25
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_5 >  -0.25
|   |   |   |   |   |   |--- feature_2 <= 0.04
|   |   |   |   |   |   |   |--- feature_4 <= 1.63
|   |   |   |   |   |   |   |   |--- feature_3 <= 0.28
|   |   |   |   |   |   |   |   |   |--- feature_7 <= -0.44
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_7 >  -0.44
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_3 >  0.28
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_4 >  1.63
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- feature_2 >  0.04
|   |   |   |   |   |   |   |--- feature_0 <= -0.31
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_0 >  -0.31
|   |   |   |   |   |   |   |   |--- class: 1
|   |--- feature_1 >  0.67
|   |   |--- feature_1 <= 1.84
|   |   |   |--- feature_1 <= 1.24
|   |   |   |   |--- feature_2 <= -3.24
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_2 >  -3.24
|   |   |   |   |   |--- feature_6 <= 0.59
|   |   |   |   |   |   |--- feature_1 <= 1.04
|   |   |   |   |   |   |   |--- feature_5 <= 2.03
|   |   |   |   |   |   |   |   |--- feature_0 <= -1.07
|   |   |   |   |   |   |   |   |   |--- feature_5 <= 1.29
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- feature_5 >  1.29
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_0 >  -1.07
|   |   |   |   |   |   |   |   |   |--- feature_4 <= 0.76
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_4 >  0.76
|   |   |   |   |   |   |   |   |   |   |--- feature_7 <= -0.82
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |   |--- feature_7 >  -0.82
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |--- feature_5 >  2.03
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_1 >  1.04
|   |   |   |   |   |   |   |--- feature_3 <= 0.21
|   |   |   |   |   |   |   |   |--- feature_7 <= -0.77
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_7 >  -0.77
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_3 >  0.21
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- feature_6 >  0.59
|   |   |   |   |   |   |--- class: 0
|   |   |   |--- feature_1 >  1.24
|   |   |   |   |--- feature_4 <= 0.94
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_4 >  0.94
|   |   |   |   |   |--- feature_5 <= 1.05
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- feature_5 >  1.05
|   |   |   |   |   |   |--- class: 0
|   |   |--- feature_1 >  1.84
|   |   |   |--- class: 1
|--- feature_7 >  -0.32
|   |--- feature_1 <= 1.31
|   |   |--- feature_1 <= -0.31
|   |   |   |--- feature_7 <= 0.31
|   |   |   |   |--- feature_5 <= -0.55
|   |   |   |   |   |--- class: 0
|   |   |   |   |--- feature_5 >  -0.55
|   |   |   |   |   |--- feature_0 <= 0.90
|   |   |   |   |   |   |--- feature_1 <= -2.12
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_1 >  -2.12
|   |   |   |   |   |   |   |--- feature_0 <= -0.01
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_0 >  -0.01
|   |   |   |   |   |   |   |   |--- feature_6 <= 1.37
|   |   |   |   |   |   |   |   |   |--- feature_1 <= -0.71
|   |   |   |   |   |   |   |   |   |   |--- feature_5 <= -0.03
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |   |--- feature_5 >  -0.03
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- feature_1 >  -0.71
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_6 >  1.37
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- feature_0 >  0.90
|   |   |   |   |   |   |--- feature_1 <= -0.97
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- feature_1 >  -0.97
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |--- feature_7 >  0.31
|   |   |   |   |--- feature_6 <= -0.59
|   |   |   |   |   |--- feature_1 <= -0.90
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_1 >  -0.90
|   |   |   |   |   |   |--- feature_2 <= 0.58
|   |   |   |   |   |   |   |--- feature_1 <= -0.33
|   |   |   |   |   |   |   |   |--- feature_6 <= -0.65
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_6 >  -0.65
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_1 >  -0.33
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_2 >  0.58
|   |   |   |   |   |   |   |--- feature_3 <= -1.22
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_3 >  -1.22
|   |   |   |   |   |   |   |   |--- feature_7 <= 1.16
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_7 >  1.16
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- feature_6 >  -0.59
|   |   |   |   |   |--- feature_5 <= -1.01
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_5 >  -1.01
|   |   |   |   |   |   |--- feature_5 <= 1.39
|   |   |   |   |   |   |   |--- feature_1 <= -3.23
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_1 >  -3.23
|   |   |   |   |   |   |   |   |--- feature_2 <= -0.63
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_2 >  -0.63
|   |   |   |   |   |   |   |   |   |--- feature_1 <= -0.69
|   |   |   |   |   |   |   |   |   |   |--- feature_0 <= 1.79
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |   |   |   |--- feature_0 >  1.79
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- feature_1 >  -0.69
|   |   |   |   |   |   |   |   |   |   |--- feature_7 <= 1.46
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 4
|   |   |   |   |   |   |   |   |   |   |--- feature_7 >  1.46
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |--- feature_5 >  1.39
|   |   |   |   |   |   |   |--- class: 1
|   |   |--- feature_1 >  -0.31
|   |   |   |--- feature_5 <= 1.23
|   |   |   |   |--- feature_1 <= 0.65
|   |   |   |   |   |--- feature_0 <= 0.21
|   |   |   |   |   |   |--- feature_2 <= -1.02
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- feature_2 >  -1.02
|   |   |   |   |   |   |   |--- feature_0 <= -0.18
|   |   |   |   |   |   |   |   |--- feature_2 <= 0.94
|   |   |   |   |   |   |   |   |   |--- feature_6 <= 1.60
|   |   |   |   |   |   |   |   |   |   |--- feature_2 <= 0.60
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |   |   |   |--- feature_2 >  0.60
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_6 >  1.60
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_2 >  0.94
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_0 >  -0.18
|   |   |   |   |   |   |   |   |--- feature_4 <= 0.36
|   |   |   |   |   |   |   |   |   |--- feature_4 <= 0.24
|   |   |   |   |   |   |   |   |   |   |--- feature_2 <= -0.27
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |   |--- feature_2 >  -0.27
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- feature_4 >  0.24
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_4 >  0.36
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_0 >  0.21
|   |   |   |   |   |   |--- feature_7 <= -0.23
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- feature_7 >  -0.23
|   |   |   |   |   |   |   |--- feature_2 <= -0.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_2 >  -0.50
|   |   |   |   |   |   |   |   |--- feature_7 <= -0.01
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_7 >  -0.01
|   |   |   |   |   |   |   |   |   |--- feature_3 <= 1.50
|   |   |   |   |   |   |   |   |   |   |--- feature_7 <= 1.97
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 15
|   |   |   |   |   |   |   |   |   |   |--- feature_7 >  1.97
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |   |   |--- feature_3 >  1.50
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_1 >  0.65
|   |   |   |   |   |--- feature_5 <= -0.34
|   |   |   |   |   |   |--- feature_5 <= -0.39
|   |   |   |   |   |   |   |--- feature_5 <= -1.21
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_5 >  -1.21
|   |   |   |   |   |   |   |   |--- feature_5 <= -0.79
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_5 >  -0.79
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 2.63
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_0 >  2.63
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_5 >  -0.39
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- feature_5 >  -0.34
|   |   |   |   |   |   |--- feature_0 <= -0.91
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- feature_0 >  -0.91
|   |   |   |   |   |   |   |--- feature_6 <= 1.11
|   |   |   |   |   |   |   |   |--- feature_7 <= 1.25
|   |   |   |   |   |   |   |   |   |--- feature_3 <= -0.36
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- feature_3 >  -0.36
|   |   |   |   |   |   |   |   |   |   |--- feature_7 <= -0.01
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |   |--- feature_7 >  -0.01
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 6
|   |   |   |   |   |   |   |   |--- feature_7 >  1.25
|   |   |   |   |   |   |   |   |   |--- feature_6 <= 0.10
|   |   |   |   |   |   |   |   |   |   |--- feature_7 <= 2.10
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |   |--- feature_7 >  2.10
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- feature_6 >  0.10
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_6 >  1.11
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |--- feature_5 >  1.23
|   |   |   |   |--- feature_7 <= 0.81
|   |   |   |   |   |--- feature_1 <= 0.03
|   |   |   |   |   |   |--- feature_1 <= -0.09
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_1 >  -0.09
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_1 >  0.03
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_7 >  0.81
|   |   |   |   |   |--- feature_7 <= 1.08
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- feature_7 >  1.08
|   |   |   |   |   |   |--- class: 0
|   |--- feature_1 >  1.31
|   |   |--- feature_5 <= -0.39
|   |   |   |--- feature_6 <= -0.57
|   |   |   |   |--- class: 1
|   |   |   |--- feature_6 >  -0.57
|   |   |   |   |--- feature_4 <= 0.24
|   |   |   |   |   |--- class: 0
|   |   |   |   |--- feature_4 >  0.24
|   |   |   |   |   |--- class: 1
|   |   |--- feature_5 >  -0.39
|   |   |   |--- feature_6 <= 2.06
|   |   |   |   |--- feature_6 <= 0.67
|   |   |   |   |   |--- feature_3 <= -1.24
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- feature_3 >  -1.24
|   |   |   |   |   |   |--- feature_1 <= 1.59
|   |   |   |   |   |   |   |--- feature_7 <= 0.59
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_7 >  0.59
|   |   |   |   |   |   |   |   |--- feature_7 <= 1.18
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_7 >  1.18
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- feature_1 >  1.59
|   |   |   |   |   |   |   |--- feature_0 <= -0.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_0 >  -0.50
|   |   |   |   |   |   |   |   |--- feature_6 <= -0.84
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_6 >  -0.84
|   |   |   |   |   |   |   |   |   |--- feature_3 <= -0.10
|   |   |   |   |   |   |   |   |   |   |--- feature_7 <= -0.04
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |   |--- feature_7 >  -0.04
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_3 >  -0.10
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_6 >  0.67
|   |   |   |   |   |--- class: 1
|   |   |   |--- feature_6 >  2.06
|   |   |   |   |--- feature_4 <= 0.24
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_4 >  0.24
|   |   |   |   |   |--- class: 0

### Visualize the tree

In [ ]:
from sklearn import tree
fig = plt.figure(figsize=(25,20))
tree.plot_tree(classifier)
plt.show()