# LAB 2 : Data Preprocessing Tools

# Import Liabraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Import Dataset

In [2]:
dataset = pd.read_csv("/content/suv_data.csv")

## EDA Steps

In [3]:
dataset.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
dataset.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [5]:
dataset.shape

(400, 5)

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB

In [7]:
# for numerical feaatures
dataset.describe()

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [8]:
# categorical features
dataset.describe(include = 'object')

        Gender
count      400
unique       2
top     Female
freq       204

## Preprocessing Steps

### Step 1 : Divide dataframe into input and output Featutres

In [10]:
# dataset.iloc [row_index,column_index]
# dataset.iloc[: , :-1]
X = dataset.iloc[:,:-1]
Y = dataset.iloc[:,-1]

In [11]:
print(X)

      User ID  Gender  Age  EstimatedSalary
0    15624510    Male   19            19000
1    15810944    Male   35            20000
2    15668575  Female   26            43000
3    15603246  Female   27            57000
4    15804002    Male   19            76000
..        ...     ...  ...              ...
395  15691863  Female   46            41000
396  15706071    Male   51            23000
397  15654296  Female   50            20000
398  15755018    Male   36            33000
399  15594041  Female   49            36000

[400 rows x 4 columns]

In [12]:
print(Y)

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

### Step 2: Handle the missing values in Dataset

In [14]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[['Age', 'EstimatedSalary']])
X[['Age', 'EstimatedSalary']] = imputer.transform(X[['Age', 'EstimatedSalary']])

In [ ]:
print(X)

   Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

## Step 3 : Encoding categorical data

#### A. Encoding the Independent Variable (i/p feature/X)

In X we have Country as categorical feature

It has 3 categories

Hence used One hot encoder

In [18]:
X['Age'].value_counts()

Age
35.0    32
37.0    20
26.0    16
42.0    16
41.0    16
39.0    15
40.0    15
48.0    14
47.0    14
27.0    13
38.0    13
36.0    12
46.0    12
28.0    12
30.0    11
31.0    11
49.0    10
29.0    10
32.0     9
24.0     9
33.0     9
60.0     7
45.0     7
19.0     7
59.0     7
20.0     7
25.0     6
52.0     6
58.0     6
23.0     6
34.0     6
18.0     5
22.0     5
57.0     5
53.0     5
21.0     4
54.0     4
50.0     4
55.0     3
51.0     3
56.0     3
43.0     3
44.0     2
Name: count, dtype: int64

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

X_transformed = dataset.iloc[:, [1, 2, 3]] # Select Gender, Age, EstimatedSalary columns

ct = ColumnTransformer(transformers=[('encoder',
                                      OneHotEncoder(),
                                      [0])],  # Apply OneHotEncoder to the first column of X_transformed (which is Gender)
                       remainder='passthrough')

X = ct.fit_transform(X_transformed)

In [23]:
print(X)

[[0.0e+00 1.0e+00 1.9e+01 1.9e+04]
 [0.0e+00 1.0e+00 3.5e+01 2.0e+04]
 [1.0e+00 0.0e+00 2.6e+01 4.3e+04]
 ...
 [1.0e+00 0.0e+00 5.0e+01 2.0e+04]
 [0.0e+00 1.0e+00 3.6e+01 3.3e+04]
 [1.0e+00 0.0e+00 4.9e+01 3.6e+04]]

Encoding the Dependent Variable (o/p feature/ target / Y)

In [24]:
Y.value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

As it has only two categoris

Hence used Label Encoder

In [25]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [26]:
print(Y)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]

### Step 4 : Splitting Data into Training and Testing

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,
                                                Y,
                                        test_size =0.3,
                                        random_state = 1)

In [29]:
print(X_train)

[[1.0e+00 0.0e+00 2.7e+01 3.1e+04]
 [1.0e+00 0.0e+00 3.5e+01 7.1e+04]
 [0.0e+00 1.0e+00 4.9e+01 2.8e+04]
 ...
 [0.0e+00 1.0e+00 5.1e+01 2.3e+04]
 [0.0e+00 1.0e+00 4.6e+01 7.9e+04]
 [0.0e+00 1.0e+00 3.0e+01 4.9e+04]]

### Step 5 : Feature Scaling

In [30]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [31]:
print(X_train)

[[ 1.          0.         27.         -1.11059025]
 [ 1.          0.         35.          0.0566968 ]
 [ 0.          1.         49.         -1.19813678]
 ...
 [ 0.          1.         51.         -1.34404767]
 [ 0.          1.         46.          0.29015421]
 [ 0.          1.         30.         -0.58531108]]